AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  cognito-app-rameez

  Sample SAM Template for cognito-app-rameez

Globals:
  Function:
    Timeout: 10

Resources:
  ExpressFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: app.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        Express:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
Outputs:
  ExpressApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ExpressFunction:
    Description: Express Lambda Function ARN
    Value: !GetAtt ExpressFunction.Arn
  ExpressFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt ExpressFunctionRole.Arn
